// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capsule.proto

#include "capsule.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_capsule_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_capsule_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_CapsuleHeader;
}  // namespace protobuf_capsule_2eproto
namespace capsule {
class CapsuleHeaderDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CapsuleHeader>
      _instance;
} _CapsuleHeader_default_instance_;
class CapsulePDUDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CapsulePDU>
      _instance;
} _CapsulePDU_default_instance_;
}  // namespace capsule
namespace protobuf_capsule_2eproto {
static void InitDefaultsCapsuleHeader() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::capsule::_CapsuleHeader_default_instance_;
    new (ptr) ::capsule::CapsuleHeader();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::capsule::CapsuleHeader::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CapsuleHeader =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCapsuleHeader}, {}};

static void InitDefaultsCapsulePDU() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::capsule::_CapsulePDU_default_instance_;
    new (ptr) ::capsule::CapsulePDU();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::capsule::CapsulePDU::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_CapsulePDU =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsCapsulePDU}, {
      &protobuf_capsule_2eproto::scc_info_CapsuleHeader.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_CapsuleHeader.base);
  ::google::protobuf::internal::InitSCC(&scc_info_CapsulePDU.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::CapsuleHeader, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::CapsuleHeader, sender_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::CapsuleHeader, prevhash_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::CapsuleHeader, hash_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::CapsuleHeader, timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::CapsuleHeader, last_logical_timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::CapsuleHeader, msgtype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::CapsuleHeader, msglen_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::CapsuleHeader, replyaddr_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::CapsuleHeader, appmeta_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::CapsuleHeader, verified_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::CapsulePDU, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::CapsulePDU, header_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::CapsulePDU, header_hash_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::CapsulePDU, signature_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::CapsulePDU, signature_len_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::CapsulePDU, payload_in_transit_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::capsule::CapsuleHeader)},
  { 15, -1, sizeof(::capsule::CapsulePDU)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::capsule::_CapsuleHeader_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::capsule::_CapsulePDU_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "capsule.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\rcapsule.proto\022\007capsule\"\312\001\n\rCapsuleHead"
      "er\022\016\n\006sender\030\001 \001(\003\022\020\n\010prevHash\030\002 \003(\014\022\014\n\004"
      "hash\030\003 \001(\014\022\021\n\ttimestamp\030\006 \001(\003\022\036\n\026last_lo"
      "gical_timestamp\030\007 \001(\003\022\017\n\007msgType\030\010 \001(\t\022\016"
      "\n\006msgLen\030\t \001(\003\022\021\n\treplyAddr\030\n \001(\t\022\017\n\007app"
      "Meta\030\013 \001(\t\022\021\n\010verified\030\241\037 \001(\010\"\217\001\n\nCapsul"
      "ePDU\022&\n\006header\030\001 \001(\0132\026.capsule.CapsuleHe"
      "ader\022\023\n\013header_hash\030\002 \001(\014\022\021\n\tsignature\030\003"
      " \001(\014\022\025\n\rsignature_len\030\004 \001(\003\022\032\n\022payload_i"
      "n_transit\030\005 \001(\014b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 383);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "capsule.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_capsule_2eproto
namespace capsule {

// ===================================================================

void CapsuleHeader::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CapsuleHeader::kSenderFieldNumber;
const int CapsuleHeader::kPrevHashFieldNumber;
const int CapsuleHeader::kHashFieldNumber;
const int CapsuleHeader::kTimestampFieldNumber;
const int CapsuleHeader::kLastLogicalTimestampFieldNumber;
const int CapsuleHeader::kMsgTypeFieldNumber;
const int CapsuleHeader::kMsgLenFieldNumber;
const int CapsuleHeader::kReplyAddrFieldNumber;
const int CapsuleHeader::kAppMetaFieldNumber;
const int CapsuleHeader::kVerifiedFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CapsuleHeader::CapsuleHeader()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_capsule_2eproto::scc_info_CapsuleHeader.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:capsule.CapsuleHeader)
}
CapsuleHeader::CapsuleHeader(const CapsuleHeader& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      prevhash_(from.prevhash_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.hash().size() > 0) {
    hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hash_);
  }
  msgtype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.msgtype().size() > 0) {
    msgtype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msgtype_);
  }
  replyaddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.replyaddr().size() > 0) {
    replyaddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.replyaddr_);
  }
  appmeta_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.appmeta().size() > 0) {
    appmeta_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.appmeta_);
  }
  ::memcpy(&sender_, &from.sender_,
    static_cast<size_t>(reinterpret_cast<char*>(&verified_) -
    reinterpret_cast<char*>(&sender_)) + sizeof(verified_));
  // @@protoc_insertion_point(copy_constructor:capsule.CapsuleHeader)
}

void CapsuleHeader::SharedCtor() {
  hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msgtype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  replyaddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  appmeta_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&sender_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&verified_) -
      reinterpret_cast<char*>(&sender_)) + sizeof(verified_));
}

CapsuleHeader::~CapsuleHeader() {
  // @@protoc_insertion_point(destructor:capsule.CapsuleHeader)
  SharedDtor();
}

void CapsuleHeader::SharedDtor() {
  hash_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msgtype_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  replyaddr_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  appmeta_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CapsuleHeader::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CapsuleHeader::descriptor() {
  ::protobuf_capsule_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_capsule_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CapsuleHeader& CapsuleHeader::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_capsule_2eproto::scc_info_CapsuleHeader.base);
  return *internal_default_instance();
}


void CapsuleHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:capsule.CapsuleHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  prevhash_.Clear();
  hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msgtype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  replyaddr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  appmeta_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&sender_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&verified_) -
      reinterpret_cast<char*>(&sender_)) + sizeof(verified_));
  _internal_metadata_.Clear();
}

bool CapsuleHeader::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:capsule.CapsuleHeader)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(32013u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 sender = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &sender_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated bytes prevHash = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_prevhash()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes hash = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_hash()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 timestamp = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 last_logical_timestamp = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &last_logical_timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string msgType = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msgtype()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->msgtype().data(), static_cast<int>(this->msgtype().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "capsule.CapsuleHeader.msgType"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 msgLen = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &msglen_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string replyAddr = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_replyaddr()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->replyaddr().data(), static_cast<int>(this->replyaddr().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "capsule.CapsuleHeader.replyAddr"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string appMeta = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u /* 90 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_appmeta()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->appmeta().data(), static_cast<int>(this->appmeta().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "capsule.CapsuleHeader.appMeta"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool verified = 4001;
      case 4001: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 32008 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &verified_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:capsule.CapsuleHeader)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:capsule.CapsuleHeader)
  return false;
#undef DO_
}

void CapsuleHeader::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:capsule.CapsuleHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 sender = 1;
  if (this->sender() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->sender(), output);
  }

  // repeated bytes prevHash = 2;
  for (int i = 0, n = this->prevhash_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->prevhash(i), output);
  }

  // bytes hash = 3;
  if (this->hash().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->hash(), output);
  }

  // int64 timestamp = 6;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(6, this->timestamp(), output);
  }

  // int64 last_logical_timestamp = 7;
  if (this->last_logical_timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(7, this->last_logical_timestamp(), output);
  }

  // string msgType = 8;
  if (this->msgtype().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msgtype().data(), static_cast<int>(this->msgtype().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "capsule.CapsuleHeader.msgType");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->msgtype(), output);
  }

  // int64 msgLen = 9;
  if (this->msglen() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(9, this->msglen(), output);
  }

  // string replyAddr = 10;
  if (this->replyaddr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->replyaddr().data(), static_cast<int>(this->replyaddr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "capsule.CapsuleHeader.replyAddr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->replyaddr(), output);
  }

  // string appMeta = 11;
  if (this->appmeta().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->appmeta().data(), static_cast<int>(this->appmeta().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "capsule.CapsuleHeader.appMeta");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->appmeta(), output);
  }

  // bool verified = 4001;
  if (this->verified() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4001, this->verified(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:capsule.CapsuleHeader)
}

::google::protobuf::uint8* CapsuleHeader::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:capsule.CapsuleHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 sender = 1;
  if (this->sender() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->sender(), target);
  }

  // repeated bytes prevHash = 2;
  for (int i = 0, n = this->prevhash_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(2, this->prevhash(i), target);
  }

  // bytes hash = 3;
  if (this->hash().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->hash(), target);
  }

  // int64 timestamp = 6;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(6, this->timestamp(), target);
  }

  // int64 last_logical_timestamp = 7;
  if (this->last_logical_timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(7, this->last_logical_timestamp(), target);
  }

  // string msgType = 8;
  if (this->msgtype().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msgtype().data(), static_cast<int>(this->msgtype().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "capsule.CapsuleHeader.msgType");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->msgtype(), target);
  }

  // int64 msgLen = 9;
  if (this->msglen() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(9, this->msglen(), target);
  }

  // string replyAddr = 10;
  if (this->replyaddr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->replyaddr().data(), static_cast<int>(this->replyaddr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "capsule.CapsuleHeader.replyAddr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->replyaddr(), target);
  }

  // string appMeta = 11;
  if (this->appmeta().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->appmeta().data(), static_cast<int>(this->appmeta().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "capsule.CapsuleHeader.appMeta");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->appmeta(), target);
  }

  // bool verified = 4001;
  if (this->verified() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4001, this->verified(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:capsule.CapsuleHeader)
  return target;
}

size_t CapsuleHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:capsule.CapsuleHeader)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated bytes prevHash = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->prevhash_size());
  for (int i = 0, n = this->prevhash_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->prevhash(i));
  }

  // bytes hash = 3;
  if (this->hash().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->hash());
  }

  // string msgType = 8;
  if (this->msgtype().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->msgtype());
  }

  // string replyAddr = 10;
  if (this->replyaddr().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->replyaddr());
  }

  // string appMeta = 11;
  if (this->appmeta().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->appmeta());
  }

  // int64 sender = 1;
  if (this->sender() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->sender());
  }

  // int64 timestamp = 6;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->timestamp());
  }

  // int64 last_logical_timestamp = 7;
  if (this->last_logical_timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->last_logical_timestamp());
  }

  // int64 msgLen = 9;
  if (this->msglen() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->msglen());
  }

  // bool verified = 4001;
  if (this->verified() != 0) {
    total_size += 3 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CapsuleHeader::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:capsule.CapsuleHeader)
  GOOGLE_DCHECK_NE(&from, this);
  const CapsuleHeader* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CapsuleHeader>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:capsule.CapsuleHeader)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:capsule.CapsuleHeader)
    MergeFrom(*source);
  }
}

void CapsuleHeader::MergeFrom(const CapsuleHeader& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:capsule.CapsuleHeader)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  prevhash_.MergeFrom(from.prevhash_);
  if (from.hash().size() > 0) {

    hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hash_);
  }
  if (from.msgtype().size() > 0) {

    msgtype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msgtype_);
  }
  if (from.replyaddr().size() > 0) {

    replyaddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.replyaddr_);
  }
  if (from.appmeta().size() > 0) {

    appmeta_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.appmeta_);
  }
  if (from.sender() != 0) {
    set_sender(from.sender());
  }
  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
  if (from.last_logical_timestamp() != 0) {
    set_last_logical_timestamp(from.last_logical_timestamp());
  }
  if (from.msglen() != 0) {
    set_msglen(from.msglen());
  }
  if (from.verified() != 0) {
    set_verified(from.verified());
  }
}

void CapsuleHeader::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:capsule.CapsuleHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CapsuleHeader::CopyFrom(const CapsuleHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:capsule.CapsuleHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CapsuleHeader::IsInitialized() const {
  return true;
}

void CapsuleHeader::Swap(CapsuleHeader* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CapsuleHeader::InternalSwap(CapsuleHeader* other) {
  using std::swap;
  prevhash_.InternalSwap(CastToBase(&other->prevhash_));
  hash_.Swap(&other->hash_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  msgtype_.Swap(&other->msgtype_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  replyaddr_.Swap(&other->replyaddr_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  appmeta_.Swap(&other->appmeta_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(sender_, other->sender_);
  swap(timestamp_, other->timestamp_);
  swap(last_logical_timestamp_, other->last_logical_timestamp_);
  swap(msglen_, other->msglen_);
  swap(verified_, other->verified_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CapsuleHeader::GetMetadata() const {
  protobuf_capsule_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_capsule_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CapsulePDU::InitAsDefaultInstance() {
  ::capsule::_CapsulePDU_default_instance_._instance.get_mutable()->header_ = const_cast< ::capsule::CapsuleHeader*>(
      ::capsule::CapsuleHeader::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CapsulePDU::kHeaderFieldNumber;
const int CapsulePDU::kHeaderHashFieldNumber;
const int CapsulePDU::kSignatureFieldNumber;
const int CapsulePDU::kSignatureLenFieldNumber;
const int CapsulePDU::kPayloadInTransitFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CapsulePDU::CapsulePDU()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_capsule_2eproto::scc_info_CapsulePDU.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:capsule.CapsulePDU)
}
CapsulePDU::CapsulePDU(const CapsulePDU& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  header_hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.header_hash().size() > 0) {
    header_hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.header_hash_);
  }
  signature_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.signature().size() > 0) {
    signature_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.signature_);
  }
  payload_in_transit_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.payload_in_transit().size() > 0) {
    payload_in_transit_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.payload_in_transit_);
  }
  if (from.has_header()) {
    header_ = new ::capsule::CapsuleHeader(*from.header_);
  } else {
    header_ = NULL;
  }
  signature_len_ = from.signature_len_;
  // @@protoc_insertion_point(copy_constructor:capsule.CapsulePDU)
}

void CapsulePDU::SharedCtor() {
  header_hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  signature_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  payload_in_transit_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&header_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&signature_len_) -
      reinterpret_cast<char*>(&header_)) + sizeof(signature_len_));
}

CapsulePDU::~CapsulePDU() {
  // @@protoc_insertion_point(destructor:capsule.CapsulePDU)
  SharedDtor();
}

void CapsulePDU::SharedDtor() {
  header_hash_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  signature_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  payload_in_transit_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete header_;
}

void CapsulePDU::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CapsulePDU::descriptor() {
  ::protobuf_capsule_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_capsule_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CapsulePDU& CapsulePDU::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_capsule_2eproto::scc_info_CapsulePDU.base);
  return *internal_default_instance();
}


void CapsulePDU::Clear() {
// @@protoc_insertion_point(message_clear_start:capsule.CapsulePDU)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  header_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  signature_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  payload_in_transit_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && header_ != NULL) {
    delete header_;
  }
  header_ = NULL;
  signature_len_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool CapsulePDU::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:capsule.CapsulePDU)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .capsule.CapsuleHeader header = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_header()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes header_hash = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_header_hash()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes signature = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_signature()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 signature_len = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &signature_len_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes payload_in_transit = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_payload_in_transit()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:capsule.CapsulePDU)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:capsule.CapsulePDU)
  return false;
#undef DO_
}

void CapsulePDU::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:capsule.CapsulePDU)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .capsule.CapsuleHeader header = 1;
  if (this->has_header()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_header(), output);
  }

  // bytes header_hash = 2;
  if (this->header_hash().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->header_hash(), output);
  }

  // bytes signature = 3;
  if (this->signature().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->signature(), output);
  }

  // int64 signature_len = 4;
  if (this->signature_len() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->signature_len(), output);
  }

  // bytes payload_in_transit = 5;
  if (this->payload_in_transit().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      5, this->payload_in_transit(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:capsule.CapsulePDU)
}

::google::protobuf::uint8* CapsulePDU::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:capsule.CapsulePDU)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .capsule.CapsuleHeader header = 1;
  if (this->has_header()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_header(), deterministic, target);
  }

  // bytes header_hash = 2;
  if (this->header_hash().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->header_hash(), target);
  }

  // bytes signature = 3;
  if (this->signature().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->signature(), target);
  }

  // int64 signature_len = 4;
  if (this->signature_len() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->signature_len(), target);
  }

  // bytes payload_in_transit = 5;
  if (this->payload_in_transit().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        5, this->payload_in_transit(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:capsule.CapsulePDU)
  return target;
}

size_t CapsulePDU::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:capsule.CapsulePDU)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes header_hash = 2;
  if (this->header_hash().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->header_hash());
  }

  // bytes signature = 3;
  if (this->signature().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->signature());
  }

  // bytes payload_in_transit = 5;
  if (this->payload_in_transit().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->payload_in_transit());
  }

  // .capsule.CapsuleHeader header = 1;
  if (this->has_header()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *header_);
  }

  // int64 signature_len = 4;
  if (this->signature_len() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->signature_len());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CapsulePDU::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:capsule.CapsulePDU)
  GOOGLE_DCHECK_NE(&from, this);
  const CapsulePDU* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CapsulePDU>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:capsule.CapsulePDU)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:capsule.CapsulePDU)
    MergeFrom(*source);
  }
}

void CapsulePDU::MergeFrom(const CapsulePDU& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:capsule.CapsulePDU)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.header_hash().size() > 0) {

    header_hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.header_hash_);
  }
  if (from.signature().size() > 0) {

    signature_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.signature_);
  }
  if (from.payload_in_transit().size() > 0) {

    payload_in_transit_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.payload_in_transit_);
  }
  if (from.has_header()) {
    mutable_header()->::capsule::CapsuleHeader::MergeFrom(from.header());
  }
  if (from.signature_len() != 0) {
    set_signature_len(from.signature_len());
  }
}

void CapsulePDU::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:capsule.CapsulePDU)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CapsulePDU::CopyFrom(const CapsulePDU& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:capsule.CapsulePDU)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CapsulePDU::IsInitialized() const {
  return true;
}

void CapsulePDU::Swap(CapsulePDU* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CapsulePDU::InternalSwap(CapsulePDU* other) {
  using std::swap;
  header_hash_.Swap(&other->header_hash_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  signature_.Swap(&other->signature_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  payload_in_transit_.Swap(&other->payload_in_transit_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(header_, other->header_);
  swap(signature_len_, other->signature_len_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CapsulePDU::GetMetadata() const {
  protobuf_capsule_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_capsule_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace capsule
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::capsule::CapsuleHeader* Arena::CreateMaybeMessage< ::capsule::CapsuleHeader >(Arena* arena) {
  return Arena::CreateInternal< ::capsule::CapsuleHeader >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::capsule::CapsulePDU* Arena::CreateMaybeMessage< ::capsule::CapsulePDU >(Arena* arena) {
  return Arena::CreateInternal< ::capsule::CapsulePDU >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
