// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

#include "request.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_capsule_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_capsule_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_CapsulePDU;
}  // namespace protobuf_capsule_2eproto
namespace capsule {
class ClientGetRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ClientGetRequest>
      _instance;
} _ClientGetRequest_default_instance_;
class ClientGetResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ClientGetResponse>
      _instance;
} _ClientGetResponse_default_instance_;
class FreshHashesContainerDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FreshHashesContainer>
      _instance;
} _FreshHashesContainer_default_instance_;
}  // namespace capsule
namespace protobuf_request_2eproto {
static void InitDefaultsClientGetRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::capsule::_ClientGetRequest_default_instance_;
    new (ptr) ::capsule::ClientGetRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::capsule::ClientGetRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ClientGetRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsClientGetRequest}, {}};

static void InitDefaultsClientGetResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::capsule::_ClientGetResponse_default_instance_;
    new (ptr) ::capsule::ClientGetResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::capsule::ClientGetResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ClientGetResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsClientGetResponse}, {
      &protobuf_capsule_2eproto::scc_info_CapsulePDU.base,}};

static void InitDefaultsFreshHashesContainer() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::capsule::_FreshHashesContainer_default_instance_;
    new (ptr) ::capsule::FreshHashesContainer();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::capsule::FreshHashesContainer::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_FreshHashesContainer =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsFreshHashesContainer}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ClientGetRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ClientGetResponse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_FreshHashesContainer.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::ClientGetRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::ClientGetRequest, hash_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::ClientGetRequest, replyaddr_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::ClientGetRequest, fresh_req_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::ClientGetRequest, metaonly_req_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::ClientGetResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::ClientGetResponse, success_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::ClientGetResponse, hash_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::ClientGetResponse, record_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::ClientGetResponse, targetaddr_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::ClientGetResponse, fresh_resp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::ClientGetResponse, fresh_hashes_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::FreshHashesContainer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::capsule::FreshHashesContainer, fresh_hashes_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::capsule::ClientGetRequest)},
  { 9, -1, sizeof(::capsule::ClientGetResponse)},
  { 20, -1, sizeof(::capsule::FreshHashesContainer)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::capsule::_ClientGetRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::capsule::_ClientGetResponse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::capsule::_FreshHashesContainer_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "request.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\rrequest.proto\022\007capsule\032\rcapsule.proto\""
      "\\\n\020ClientGetRequest\022\014\n\004hash\030\001 \001(\014\022\021\n\trep"
      "lyAddr\030\002 \001(\t\022\021\n\tfresh_req\030\003 \001(\010\022\024\n\014metao"
      "nly_req\030\004 \001(\010\"\225\001\n\021ClientGetResponse\022\017\n\007s"
      "uccess\030\001 \001(\010\022\014\n\004hash\030\002 \001(\014\022#\n\006record\030\003 \001"
      "(\0132\023.capsule.CapsulePDU\022\022\n\ntargetAddr\030\004 "
      "\001(\t\022\022\n\nfresh_resp\030\005 \001(\010\022\024\n\014fresh_hashes\030"
      "\006 \003(\014\",\n\024FreshHashesContainer\022\024\n\014fresh_h"
      "ashes\030\001 \003(\014b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 339);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "request.proto", &protobuf_RegisterTypes);
  ::protobuf_capsule_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_request_2eproto
namespace capsule {

// ===================================================================

void ClientGetRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientGetRequest::kHashFieldNumber;
const int ClientGetRequest::kReplyAddrFieldNumber;
const int ClientGetRequest::kFreshReqFieldNumber;
const int ClientGetRequest::kMetaonlyReqFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientGetRequest::ClientGetRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_request_2eproto::scc_info_ClientGetRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:capsule.ClientGetRequest)
}
ClientGetRequest::ClientGetRequest(const ClientGetRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.hash().size() > 0) {
    hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hash_);
  }
  replyaddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.replyaddr().size() > 0) {
    replyaddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.replyaddr_);
  }
  ::memcpy(&fresh_req_, &from.fresh_req_,
    static_cast<size_t>(reinterpret_cast<char*>(&metaonly_req_) -
    reinterpret_cast<char*>(&fresh_req_)) + sizeof(metaonly_req_));
  // @@protoc_insertion_point(copy_constructor:capsule.ClientGetRequest)
}

void ClientGetRequest::SharedCtor() {
  hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  replyaddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&fresh_req_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&metaonly_req_) -
      reinterpret_cast<char*>(&fresh_req_)) + sizeof(metaonly_req_));
}

ClientGetRequest::~ClientGetRequest() {
  // @@protoc_insertion_point(destructor:capsule.ClientGetRequest)
  SharedDtor();
}

void ClientGetRequest::SharedDtor() {
  hash_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  replyaddr_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ClientGetRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ClientGetRequest::descriptor() {
  ::protobuf_request_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_request_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ClientGetRequest& ClientGetRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_request_2eproto::scc_info_ClientGetRequest.base);
  return *internal_default_instance();
}


void ClientGetRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:capsule.ClientGetRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  replyaddr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&fresh_req_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&metaonly_req_) -
      reinterpret_cast<char*>(&fresh_req_)) + sizeof(metaonly_req_));
  _internal_metadata_.Clear();
}

bool ClientGetRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:capsule.ClientGetRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes hash = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_hash()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string replyAddr = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_replyaddr()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->replyaddr().data(), static_cast<int>(this->replyaddr().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "capsule.ClientGetRequest.replyAddr"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool fresh_req = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &fresh_req_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool metaonly_req = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &metaonly_req_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:capsule.ClientGetRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:capsule.ClientGetRequest)
  return false;
#undef DO_
}

void ClientGetRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:capsule.ClientGetRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes hash = 1;
  if (this->hash().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->hash(), output);
  }

  // string replyAddr = 2;
  if (this->replyaddr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->replyaddr().data(), static_cast<int>(this->replyaddr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "capsule.ClientGetRequest.replyAddr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->replyaddr(), output);
  }

  // bool fresh_req = 3;
  if (this->fresh_req() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->fresh_req(), output);
  }

  // bool metaonly_req = 4;
  if (this->metaonly_req() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->metaonly_req(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:capsule.ClientGetRequest)
}

::google::protobuf::uint8* ClientGetRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:capsule.ClientGetRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes hash = 1;
  if (this->hash().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->hash(), target);
  }

  // string replyAddr = 2;
  if (this->replyaddr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->replyaddr().data(), static_cast<int>(this->replyaddr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "capsule.ClientGetRequest.replyAddr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->replyaddr(), target);
  }

  // bool fresh_req = 3;
  if (this->fresh_req() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->fresh_req(), target);
  }

  // bool metaonly_req = 4;
  if (this->metaonly_req() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->metaonly_req(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:capsule.ClientGetRequest)
  return target;
}

size_t ClientGetRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:capsule.ClientGetRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes hash = 1;
  if (this->hash().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->hash());
  }

  // string replyAddr = 2;
  if (this->replyaddr().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->replyaddr());
  }

  // bool fresh_req = 3;
  if (this->fresh_req() != 0) {
    total_size += 1 + 1;
  }

  // bool metaonly_req = 4;
  if (this->metaonly_req() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ClientGetRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:capsule.ClientGetRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ClientGetRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ClientGetRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:capsule.ClientGetRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:capsule.ClientGetRequest)
    MergeFrom(*source);
  }
}

void ClientGetRequest::MergeFrom(const ClientGetRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:capsule.ClientGetRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.hash().size() > 0) {

    hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hash_);
  }
  if (from.replyaddr().size() > 0) {

    replyaddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.replyaddr_);
  }
  if (from.fresh_req() != 0) {
    set_fresh_req(from.fresh_req());
  }
  if (from.metaonly_req() != 0) {
    set_metaonly_req(from.metaonly_req());
  }
}

void ClientGetRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:capsule.ClientGetRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientGetRequest::CopyFrom(const ClientGetRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:capsule.ClientGetRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientGetRequest::IsInitialized() const {
  return true;
}

void ClientGetRequest::Swap(ClientGetRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientGetRequest::InternalSwap(ClientGetRequest* other) {
  using std::swap;
  hash_.Swap(&other->hash_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  replyaddr_.Swap(&other->replyaddr_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(fresh_req_, other->fresh_req_);
  swap(metaonly_req_, other->metaonly_req_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ClientGetRequest::GetMetadata() const {
  protobuf_request_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_request_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ClientGetResponse::InitAsDefaultInstance() {
  ::capsule::_ClientGetResponse_default_instance_._instance.get_mutable()->record_ = const_cast< ::capsule::CapsulePDU*>(
      ::capsule::CapsulePDU::internal_default_instance());
}
void ClientGetResponse::clear_record() {
  if (GetArenaNoVirtual() == NULL && record_ != NULL) {
    delete record_;
  }
  record_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientGetResponse::kSuccessFieldNumber;
const int ClientGetResponse::kHashFieldNumber;
const int ClientGetResponse::kRecordFieldNumber;
const int ClientGetResponse::kTargetAddrFieldNumber;
const int ClientGetResponse::kFreshRespFieldNumber;
const int ClientGetResponse::kFreshHashesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientGetResponse::ClientGetResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_request_2eproto::scc_info_ClientGetResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:capsule.ClientGetResponse)
}
ClientGetResponse::ClientGetResponse(const ClientGetResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      fresh_hashes_(from.fresh_hashes_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.hash().size() > 0) {
    hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hash_);
  }
  targetaddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.targetaddr().size() > 0) {
    targetaddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.targetaddr_);
  }
  if (from.has_record()) {
    record_ = new ::capsule::CapsulePDU(*from.record_);
  } else {
    record_ = NULL;
  }
  ::memcpy(&success_, &from.success_,
    static_cast<size_t>(reinterpret_cast<char*>(&fresh_resp_) -
    reinterpret_cast<char*>(&success_)) + sizeof(fresh_resp_));
  // @@protoc_insertion_point(copy_constructor:capsule.ClientGetResponse)
}

void ClientGetResponse::SharedCtor() {
  hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  targetaddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&record_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&fresh_resp_) -
      reinterpret_cast<char*>(&record_)) + sizeof(fresh_resp_));
}

ClientGetResponse::~ClientGetResponse() {
  // @@protoc_insertion_point(destructor:capsule.ClientGetResponse)
  SharedDtor();
}

void ClientGetResponse::SharedDtor() {
  hash_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  targetaddr_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete record_;
}

void ClientGetResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ClientGetResponse::descriptor() {
  ::protobuf_request_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_request_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ClientGetResponse& ClientGetResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_request_2eproto::scc_info_ClientGetResponse.base);
  return *internal_default_instance();
}


void ClientGetResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:capsule.ClientGetResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  fresh_hashes_.Clear();
  hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  targetaddr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && record_ != NULL) {
    delete record_;
  }
  record_ = NULL;
  ::memset(&success_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&fresh_resp_) -
      reinterpret_cast<char*>(&success_)) + sizeof(fresh_resp_));
  _internal_metadata_.Clear();
}

bool ClientGetResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:capsule.ClientGetResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool success = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &success_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes hash = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_hash()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .capsule.CapsulePDU record = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_record()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string targetAddr = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_targetaddr()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->targetaddr().data(), static_cast<int>(this->targetaddr().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "capsule.ClientGetResponse.targetAddr"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool fresh_resp = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &fresh_resp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated bytes fresh_hashes = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_fresh_hashes()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:capsule.ClientGetResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:capsule.ClientGetResponse)
  return false;
#undef DO_
}

void ClientGetResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:capsule.ClientGetResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->success() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->success(), output);
  }

  // bytes hash = 2;
  if (this->hash().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->hash(), output);
  }

  // .capsule.CapsulePDU record = 3;
  if (this->has_record()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_record(), output);
  }

  // string targetAddr = 4;
  if (this->targetaddr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->targetaddr().data(), static_cast<int>(this->targetaddr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "capsule.ClientGetResponse.targetAddr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->targetaddr(), output);
  }

  // bool fresh_resp = 5;
  if (this->fresh_resp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->fresh_resp(), output);
  }

  // repeated bytes fresh_hashes = 6;
  for (int i = 0, n = this->fresh_hashes_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      6, this->fresh_hashes(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:capsule.ClientGetResponse)
}

::google::protobuf::uint8* ClientGetResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:capsule.ClientGetResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->success() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->success(), target);
  }

  // bytes hash = 2;
  if (this->hash().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->hash(), target);
  }

  // .capsule.CapsulePDU record = 3;
  if (this->has_record()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_record(), deterministic, target);
  }

  // string targetAddr = 4;
  if (this->targetaddr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->targetaddr().data(), static_cast<int>(this->targetaddr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "capsule.ClientGetResponse.targetAddr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->targetaddr(), target);
  }

  // bool fresh_resp = 5;
  if (this->fresh_resp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->fresh_resp(), target);
  }

  // repeated bytes fresh_hashes = 6;
  for (int i = 0, n = this->fresh_hashes_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(6, this->fresh_hashes(i), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:capsule.ClientGetResponse)
  return target;
}

size_t ClientGetResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:capsule.ClientGetResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated bytes fresh_hashes = 6;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->fresh_hashes_size());
  for (int i = 0, n = this->fresh_hashes_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->fresh_hashes(i));
  }

  // bytes hash = 2;
  if (this->hash().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->hash());
  }

  // string targetAddr = 4;
  if (this->targetaddr().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->targetaddr());
  }

  // .capsule.CapsulePDU record = 3;
  if (this->has_record()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *record_);
  }

  // bool success = 1;
  if (this->success() != 0) {
    total_size += 1 + 1;
  }

  // bool fresh_resp = 5;
  if (this->fresh_resp() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ClientGetResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:capsule.ClientGetResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ClientGetResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ClientGetResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:capsule.ClientGetResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:capsule.ClientGetResponse)
    MergeFrom(*source);
  }
}

void ClientGetResponse::MergeFrom(const ClientGetResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:capsule.ClientGetResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  fresh_hashes_.MergeFrom(from.fresh_hashes_);
  if (from.hash().size() > 0) {

    hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hash_);
  }
  if (from.targetaddr().size() > 0) {

    targetaddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.targetaddr_);
  }
  if (from.has_record()) {
    mutable_record()->::capsule::CapsulePDU::MergeFrom(from.record());
  }
  if (from.success() != 0) {
    set_success(from.success());
  }
  if (from.fresh_resp() != 0) {
    set_fresh_resp(from.fresh_resp());
  }
}

void ClientGetResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:capsule.ClientGetResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientGetResponse::CopyFrom(const ClientGetResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:capsule.ClientGetResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientGetResponse::IsInitialized() const {
  return true;
}

void ClientGetResponse::Swap(ClientGetResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientGetResponse::InternalSwap(ClientGetResponse* other) {
  using std::swap;
  fresh_hashes_.InternalSwap(CastToBase(&other->fresh_hashes_));
  hash_.Swap(&other->hash_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  targetaddr_.Swap(&other->targetaddr_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(record_, other->record_);
  swap(success_, other->success_);
  swap(fresh_resp_, other->fresh_resp_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ClientGetResponse::GetMetadata() const {
  protobuf_request_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_request_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void FreshHashesContainer::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FreshHashesContainer::kFreshHashesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FreshHashesContainer::FreshHashesContainer()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_request_2eproto::scc_info_FreshHashesContainer.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:capsule.FreshHashesContainer)
}
FreshHashesContainer::FreshHashesContainer(const FreshHashesContainer& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      fresh_hashes_(from.fresh_hashes_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:capsule.FreshHashesContainer)
}

void FreshHashesContainer::SharedCtor() {
}

FreshHashesContainer::~FreshHashesContainer() {
  // @@protoc_insertion_point(destructor:capsule.FreshHashesContainer)
  SharedDtor();
}

void FreshHashesContainer::SharedDtor() {
}

void FreshHashesContainer::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* FreshHashesContainer::descriptor() {
  ::protobuf_request_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_request_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const FreshHashesContainer& FreshHashesContainer::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_request_2eproto::scc_info_FreshHashesContainer.base);
  return *internal_default_instance();
}


void FreshHashesContainer::Clear() {
// @@protoc_insertion_point(message_clear_start:capsule.FreshHashesContainer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  fresh_hashes_.Clear();
  _internal_metadata_.Clear();
}

bool FreshHashesContainer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:capsule.FreshHashesContainer)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated bytes fresh_hashes = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_fresh_hashes()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:capsule.FreshHashesContainer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:capsule.FreshHashesContainer)
  return false;
#undef DO_
}

void FreshHashesContainer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:capsule.FreshHashesContainer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated bytes fresh_hashes = 1;
  for (int i = 0, n = this->fresh_hashes_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->fresh_hashes(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:capsule.FreshHashesContainer)
}

::google::protobuf::uint8* FreshHashesContainer::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:capsule.FreshHashesContainer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated bytes fresh_hashes = 1;
  for (int i = 0, n = this->fresh_hashes_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(1, this->fresh_hashes(i), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:capsule.FreshHashesContainer)
  return target;
}

size_t FreshHashesContainer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:capsule.FreshHashesContainer)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated bytes fresh_hashes = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->fresh_hashes_size());
  for (int i = 0, n = this->fresh_hashes_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->fresh_hashes(i));
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FreshHashesContainer::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:capsule.FreshHashesContainer)
  GOOGLE_DCHECK_NE(&from, this);
  const FreshHashesContainer* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FreshHashesContainer>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:capsule.FreshHashesContainer)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:capsule.FreshHashesContainer)
    MergeFrom(*source);
  }
}

void FreshHashesContainer::MergeFrom(const FreshHashesContainer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:capsule.FreshHashesContainer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  fresh_hashes_.MergeFrom(from.fresh_hashes_);
}

void FreshHashesContainer::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:capsule.FreshHashesContainer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FreshHashesContainer::CopyFrom(const FreshHashesContainer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:capsule.FreshHashesContainer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FreshHashesContainer::IsInitialized() const {
  return true;
}

void FreshHashesContainer::Swap(FreshHashesContainer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FreshHashesContainer::InternalSwap(FreshHashesContainer* other) {
  using std::swap;
  fresh_hashes_.InternalSwap(CastToBase(&other->fresh_hashes_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata FreshHashesContainer::GetMetadata() const {
  protobuf_request_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_request_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace capsule
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::capsule::ClientGetRequest* Arena::CreateMaybeMessage< ::capsule::ClientGetRequest >(Arena* arena) {
  return Arena::CreateInternal< ::capsule::ClientGetRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::capsule::ClientGetResponse* Arena::CreateMaybeMessage< ::capsule::ClientGetResponse >(Arena* arena) {
  return Arena::CreateInternal< ::capsule::ClientGetResponse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::capsule::FreshHashesContainer* Arena::CreateMaybeMessage< ::capsule::FreshHashesContainer >(Arena* arena) {
  return Arena::CreateInternal< ::capsule::FreshHashesContainer >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
